<?php

$hero = array(
    'key' => 'layout_6437c84786c46',
    'name' => 'hero',
    'label' => 'Hero',
    'display' => 'block',
    'sub_fields' => array(
        array(
            'key' => 'field_6437c654e39fc',
            'label' => 'Heading',
            'name' => 'heading',
            'aria-label' => '',
            'type' => 'text',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '80',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'maxlength' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
        ),
        array(
            'key' => 'field_6437c6c8e39fd',
            'label' => 'Heading Tag',
            'name' => 'heading_tag',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '20',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'h1' => 'h1',
                'h2' => 'h2',
                'h3' => 'h3',
                'h4' => 'h4',
                'h5' => 'h5',
                'h6' => 'h6',
                'div' => 'div',
            ),
            'default_value' => false,
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 0,
            'ajax' => 0,
            'placeholder' => '',
        ),
        array(
            'key' => 'field_6437c6fae39fe',
            'label' => 'Text',
            'name' => 'text',
            'aria-label' => '',
            'type' => 'wysiwyg',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'tabs' => 'all',
            'toolbar' => 'full',
            'media_upload' => 0,
            'delay' => 0,
        ),
        array(
            'key' => 'field_643ff5b2466a4',
            'label' => 'Link',
            'name' => 'link',
            'aria-label' => '',
            'type' => 'link',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
        ),
        array(
            'key' => 'field_643ff5c8466a5',
            'label' => 'Text zentrieren?',
            'name' => 'is_text_centered',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_6437efa357cc4',
            'label' => 'Höhe',
            'name' => 'height',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'height100' => 'Ganzer Bildschirm',
                'height50' => 'Halber Bildschirm',
            ),
            'default_value' => 'height50',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'horizontal',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_643815004e5b0',
            'label' => 'Overlay',
            'name' => 'background_overlay',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '100',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'dark' => 'Dunkel',
                'light' => 'Hell',
            ),
            'default_value' => 'dark',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'horizontal',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_6437c70ee39ff',
            'label' => 'Hintergrund Element',
            'name' => 'background_element',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'color' => 'Hintergrund Farbe',
                'image' => 'Hintergrund Bild',
                'video' => 'Hintergrund Video',
                'textOnly' => 'Text Only',
                'slider' => 'Hintergrund Slider',
            ),
            'default_value' => '',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'horizontal',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_6437c7e9e3a00',
            'label' => 'Hintergrundbild',
            'name' => 'background_image',
            'aria-label' => '',
            'type' => 'image',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '==',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'color',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'video',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'slider',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '.jpg, .jpeg, .png, .webp, .bmp',
            'preview_size' => 'medium',
        ),
        array(
            'key' => 'field_6437ea313f542',
            'label' => 'Hintergrundvideo',
            'name' => 'background_video',
            'aria-label' => '',
            'type' => 'file',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '==',
                        'value' => 'video',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'color',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'slider',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min_size' => '',
            'max_size' => '',
            'mime_types' => '.mp4, .m4p, .wmv, .avi, .webm, .flv, .gifv, .mpg, .mp2, .mpeg, .mpe, .mpv',
        ),
        array(
            'key' => 'field_6437f8f1d262b',
            'label' => 'Hintergrundslider',
            'name' => 'background_slider',
            'aria-label' => '',
            'type' => 'gallery',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '==',
                        'value' => 'slider',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'color',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'video',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'textOnly',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'return_format' => 'array',
            'library' => 'all',
            'min' => '',
            'max' => '',
            'min_width' => '',
            'min_height' => '',
            'min_size' => '',
            'max_width' => '',
            'max_height' => '',
            'max_size' => '',
            'mime_types' => '.jpg, .jpeg, .png, .webp, .bmp',
            'insert' => 'append',
            'preview_size' => 'medium',
        ),
        array(
            'key' => 'field_6437e904bd894',
            'label' => 'Hintergrundfarbe',
            'name' => 'background_color',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 1,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '==',
                        'value' => 'color',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'slider',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'video',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'Primary' => 'Primary',
                'Secondary' => 'Secondary',
            ),
            'default_value' => '',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'horizontal',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_644911ec53f9f',
            'label' => 'Punkte anzeigen',
            'name' => 'use_dots',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '==',
                        'value' => 'slider',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'color',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'video',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'textOnly',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_644911a853f9e',
            'label' => 'Pfeile anzeigen',
            'name' => 'use_arrows',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '==',
                        'value' => 'slider',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'color',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'video',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'textOnly',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_64491c6103a5e',
            'label' => 'Animation',
            'name' => 'carousel_animation',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '==',
                        'value' => 'slider',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'color',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'video',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'textOnly',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'fade' => 'Fade',
                'slide' => 'Slide',
            ),
            'default_value' => 'fade',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'horizontal',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_64492a262c717',
            'label' => 'Autoplay',
            'name' => 'carousel_autoplay',
            'aria-label' => '',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '==',
                        'value' => 'slider',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'color',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'video',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'textOnly',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '25',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'true' => 'Ein',
                'false' => 'Aus',
            ),
            'default_value' => 'true',
            'return_format' => 'value',
            'allow_null' => 0,
            'other_choice' => 0,
            'layout' => 'horizontal',
            'save_other_choice' => 0,
        ),
        array(
            'key' => 'field_64491801f3c46',
            'label' => 'Autoplay Intervall',
            'name' => 'autoplay_interval',
            'aria-label' => '',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '==',
                        'value' => 'slider',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'color',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'image',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'video',
                    ),
                    array(
                        'field' => 'field_6437c70ee39ff',
                        'operator' => '!=',
                        'value' => 'textOnly',
                    ),
                    array(
                        'field' => 'field_64492a262c717',
                        'operator' => '==',
                        'value' => 'true',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                '3s' => '3s',
                '4s' => '4s',
                '5s' => '5s',
                '6s' => '6s',
                '7s' => '7s',
                '8s' => '8s',
                '9s' => '9s',
                '10s' => '10s',
            ),
            'default_value' => '5s',
            'return_format' => 'value',
            'multiple' => 0,
            'allow_null' => 0,
            'ui' => 1,
            'ajax' => 1,
            'placeholder' => '',
        ),
    ),
    'min' => '',
    'max' => '',
);