<?php

acf_add_local_field_group(
    array(
        'key' => 'group_651e4e8db578a',
        'title' => 'Back To Top',
        'fields' => array(
            array(
                'key' => 'field_65533a5f4cca1',
                'label' => 'Back To Top Button Image',
                'name' => 'back_to_top_button_image',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => 4,
                'mime_types' => 'jpg, jpeg, gif, png, apng, svg, bmp, bmp, ico, png',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_65533a704cca2',
                'label' => 'Back To Top Button Hintergrund Farbe',
                'name' => 'back_to_top_button_background_color',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'white' => 'White',
                    'black' => 'Black',
                    'primary' => 'Primary',
                    'secondary' => 'Secondary',
                ),
                'default_value' => 'primary : Primary',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'vertical',
                'save_other_choice' => 0,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-back-to-top-button',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'backToTop',
        'map_graphql_types_from_location_rules' => 0,
        'graphql_types' => '',
    )
);