<?php

acf_add_local_field_group(
    array(
        'key' => 'group_64522249b23f0',
        'title' => 'Navigation',
        'fields' => array(
            array(
                'key' => 'field_651e4e8d18fd2',
                'label' => 'Logo',
                'name' => 'navigation_logo',
                'aria-label' => '',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'id',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
                'preview_size' => 'medium',
            ),
            array(
                'key' => 'field_6464bee05bd4a',
                'label' => 'Main Menu DE',
                'name' => 'main_menu_de',
                'aria-label' => '',
                'type' => 'group',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'layout' => 'block',
                'sub_fields' => array(
                    array(
                        'key' => 'field_6464c1f4766ce',
                        'label' => 'Menu Item',
                        'name' => 'menu_item',
                        'aria-label' => '',
                        'type' => 'repeater',
                        'instructions' => '',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'row',
                        'pagination' => 0,
                        'min' => 1,
                        'max' => 5,
                        'collapsed' => '',
                        'button_label' => 'Add Row',
                        'rows_per_page' => 20,
                        'sub_fields' => array(
                            array(
                                'key' => 'field_6464bef45bd4b',
                                'label' => 'Menu Type',
                                'name' => 'menu_type',
                                'aria-label' => '',
                                'type' => 'select',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => 0,
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'choices' => array(
                                    'link' => 'Link',
                                    'dropdown' => 'Dropdown',
                                    'mega' => 'Mega Menü',
                                ),
                                'default_value' => 'link',
                                'return_format' => 'value',
                                'multiple' => 0,
                                'allow_null' => 0,
                                'ui' => 0,
                                'ajax' => 0,
                                'placeholder' => '',
                                'parent_repeater' => 'field_6464c1f4766ce',
                            ),
                            array(
                                'key' => 'field_646c6e662d80a',
                                'label' => 'Link',
                                'name' => 'link',
                                'aria-label' => '',
                                'type' => 'link',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_6464bef45bd4b',
                                            'operator' => '==',
                                            'value' => 'link',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'return_format' => 'array',
                                'parent_repeater' => 'field_6464c1f4766ce',
                            ),
                            array(
                                'key' => 'field_6464bf6f5bd4d',
                                'label' => 'Dropdown',
                                'name' => 'dropdown',
                                'aria-label' => '',
                                'type' => 'repeater',
                                'instructions' => '',
                                'required' => 1,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_6464bef45bd4b',
                                            'operator' => '==',
                                            'value' => 'dropdown',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'min' => 1,
                                'max' => 1,
                                'collapsed' => '',
                                'button_label' => 'Add Row',
                                'layout' => 'row',
                                'rows_per_page' => 20,
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_6464bf8e5bd4f',
                                        'label' => 'Link',
                                        'name' => 'link',
                                        'aria-label' => '',
                                        'type' => 'link',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'return_format' => 'array',
                                        'parent_repeater' => 'field_6464bf6f5bd4d',
                                    ),
                                    array(
                                        'key' => 'field_6464bfa55bd50',
                                        'label' => 'Sub Links',
                                        'name' => 'sub_links',
                                        'aria-label' => '',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layout' => 'table',
                                        'min' => 1,
                                        'max' => 10,
                                        'collapsed' => '',
                                        'button_label' => 'Add Row',
                                        'rows_per_page' => 20,
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_6464bfa55bd51',
                                                'label' => 'Sub Link',
                                                'name' => 'sub_link',
                                                'aria-label' => '',
                                                'type' => 'link',
                                                'instructions' => '',
                                                'required' => 1,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'array',
                                                'parent_repeater' => 'field_6464bfa55bd50',
                                            ),
                                        ),
                                        'parent_repeater' => 'field_6464bf6f5bd4d',
                                    ),
                                ),
                                'parent_repeater' => 'field_6464c1f4766ce',
                            ),
                            array(
                                'key' => 'field_6464bfe55bd52',
                                'label' => 'MegaMenu',
                                'name' => 'mega_menu',
                                'aria-label' => '',
                                'type' => 'group',
                                'instructions' => '',
                                'required' => 0,
                                'conditional_logic' => array(
                                    array(
                                        array(
                                            'field' => 'field_6464bef45bd4b',
                                            'operator' => '==',
                                            'value' => 'mega',
                                        ),
                                    ),
                                ),
                                'wrapper' => array(
                                    'width' => '25',
                                    'class' => '',
                                    'id' => '',
                                ),
                                'layout' => 'block',
                                'sub_fields' => array(
                                    array(
                                        'key' => 'field_646c8ee763407',
                                        'label' => 'Title',
                                        'name' => 'title',
                                        'aria-label' => '',
                                        'type' => 'text',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'default_value' => '',
                                        'maxlength' => '',
                                        'placeholder' => '',
                                        'prepend' => '',
                                        'append' => '',
                                    ),
                                    array(
                                        'key' => 'field_6464c14ae3d0d',
                                        'label' => 'SubMenu',
                                        'name' => 'submenu',
                                        'aria-label' => '',
                                        'type' => 'repeater',
                                        'instructions' => '',
                                        'required' => 1,
                                        'conditional_logic' => 0,
                                        'wrapper' => array(
                                            'width' => '',
                                            'class' => '',
                                            'id' => '',
                                        ),
                                        'layout' => 'row',
                                        'pagination' => 0,
                                        'min' => 1,
                                        'max' => 0,
                                        'collapsed' => '',
                                        'button_label' => 'Add Row',
                                        'rows_per_page' => 20,
                                        'sub_fields' => array(
                                            array(
                                                'key' => 'field_6464c117e3d0a',
                                                'label' => 'Link',
                                                'name' => 'link',
                                                'aria-label' => '',
                                                'type' => 'link',
                                                'instructions' => '',
                                                'required' => 1,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'return_format' => 'array',
                                                'parent_repeater' => 'field_6464c14ae3d0d',
                                            ),
                                            array(
                                                'key' => 'field_6464c124e3d0b',
                                                'label' => 'Sub Links',
                                                'name' => 'sub_links',
                                                'aria-label' => '',
                                                'type' => 'repeater',
                                                'instructions' => '',
                                                'required' => 1,
                                                'conditional_logic' => 0,
                                                'wrapper' => array(
                                                    'width' => '',
                                                    'class' => '',
                                                    'id' => '',
                                                ),
                                                'layout' => 'table',
                                                'min' => 1,
                                                'max' => 8,
                                                'collapsed' => '',
                                                'button_label' => 'Add Row',
                                                'rows_per_page' => 20,
                                                'sub_fields' => array(
                                                    array(
                                                        'key' => 'field_6464c124e3d0c',
                                                        'label' => 'Sub Link',
                                                        'name' => 'sub_link',
                                                        'aria-label' => '',
                                                        'type' => 'link',
                                                        'instructions' => '',
                                                        'required' => 1,
                                                        'conditional_logic' => 0,
                                                        'wrapper' => array(
                                                            'width' => '',
                                                            'class' => '',
                                                            'id' => '',
                                                        ),
                                                        'return_format' => 'array',
                                                        'parent_repeater' => 'field_6464c124e3d0b',
                                                    ),
                                                ),
                                                'parent_repeater' => 'field_6464c14ae3d0d',
                                            ),
                                        ),
                                    ),
                                ),
                                'parent_repeater' => 'field_6464c1f4766ce',
                            ),
                        ),
                    ),
                ),
            ),
            array(
                'key' => 'field_6453abc3e6a3a',
                'label' => 'Slide In Direction (Mobile)',
                'name' => 'slide_in_direction_mobile',
                'aria-label' => '',
                'type' => 'select',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'left' => 'Links nach Rechts',
                    'right' => 'Rechts nach Links',
                ),
                'default_value' => 'left',
                'return_format' => 'value',
                'multiple' => 0,
                'allow_null' => 0,
                'ui' => 0,
                'ajax' => 0,
                'placeholder' => '',
            ),
            array(
                'key' => 'field_6475c57bd9eb5',
                'label' => 'Border Bottom Color',
                'name' => 'border_bottom_color',
                'aria-label' => '',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'None' => 'None',
                    'Brand' => 'Brand',
                    'Primary' => 'Primary',
                    'Secondary' => 'Secondary',
                    'Black' => 'Black',
                    'White' => 'White',
                ),
                'default_value' => 'None',
                'return_format' => 'value',
                'allow_null' => 0,
                'other_choice' => 0,
                'layout' => 'vertical',
                'save_other_choice' => 0,
            ),
            array(
                'key' => 'field_6475c5cbd9eb6',
                'label' => 'Language Switch Button einblenden',
                'name' => 'show_language_switch',
                'aria-label' => '',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 0,
                'ui_on_text' => '',
                'ui_off_text' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-navigation',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'optionsNavigation',
        'map_graphql_types_from_location_rules' => 0,
        'graphql_types' => '',
    )
);